name: deploy-client 

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create .env.production from GitHub Secrets
      - name: Create .env.production
        run: |
          cd client
          cat << EOF > .env.production
          NEXT_PUBLIC_API_URL=${{ secrets.DOCKER_USERNAME }}
          # Add all your NEXT_PUBLIC_* variables here
          EOF
      
      - run: cd client && docker build -f Dockerfile.prod -t rosengray/sima-client . --no-cache
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rosengray/sima-client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save sima
      - run: kubectl rollout restart deployment client-depl
